### PR TITLE
Styling and some other stuff

### PR DESCRIPTION
**Pull request by Reinachan**
I put notes into each commit explaining most of the changes

### CODE REVIEW

**Review by toyhammered — CHANGES_REQUESTED** [review]
This is great! I do think we should be using `font-awesome` to handle all the icons for us instead of importing.

**Comment by Reinachan** [comment]
I don't mind using Font Awesome. I believe I just dismissed it because I thought it was paid only or something. I'll look into it more later today

**Comment by toyhammered** [comment]
I'm pretty sure they have a free tier?

**Comment by Reinachan** [comment]
Replaced icons with font-awesome alternatives

**Review by toyhammered — APPROVED** [review]

**Pull request merged**
